import Head from "next/head";
import { useState } from "react";
import styles from "./Layout.module.css";
import QuestionBlock from "../QuestionBlock/QuestionBlock";

const Layout = ({ title = "Country Quiz !", countries }) => {
  const [state, setState] = useState("");

  let numbers = [];
  let fourNumbers = [];
  let listQuestion = [{}, {}, {}, {}];
  const uniqueNumber = () => {
    const number = Math.floor(Math.random() * countries.length + 1);
    if (!numbers.includes(number)) {
      numbers.push(number);
      return number;
    } else if (numbers.length - 1 !== countries.length) {
      uniqueNumber();
    }
  };
  const generateFourUniqueNumber = () => {
    numbers = [];
    for (var j = 0; j < 4; j++) {
      uniqueNumber();
    }
  };
  const generateQuestion = () => {
    for (var i = 0; i < 4; i++) {
      generateFourUniqueNumber();
      let randomAnswer = Math.floor(Math.random() * 4);
      listQuestion[i]["typeQuestion"] = 0;
      listQuestion[i]["titreQuestion"] =
        countries[numbers[randomAnswer]].capital;
      listQuestion[i]["listAnswer"] = [{}, {}, {}, {}];
      for (var j = 0; j < 4; j++) {
        listQuestion[i]["listAnswer"][j]["nameCountry"] =
          countries[numbers[j]].name;
        let isCorrect = false;
        if (j == randomAnswer) {
          isCorrect = true;
        }
        listQuestion[i]["listAnswer"][j]["isCorrect"] = isCorrect;
        listQuestion[i]["listAnswer"][j]["wasClicked"] = false;
      }
    }
  };
  const restartQuiz = () => {
    numbers = [];
    listQuestion = [{}, {}, {}, {}];
    generateQuestion();
    setState({});
  };
  generateQuestion();
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Country Quiz</h1>

        <div className={styles.corps}>
          <QuestionBlock
            questions={listQuestion}
            generateQuestion={restartQuiz}
          />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};
export default Layout;
